name: Application Update Pipeline

on:
  push:
     branches:
      - master
     paths:
      - db_load.py
      - main.py
      - requirements.txt
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Copy Updated files to S3
        run: |
          aws s3 cp main.py s3://rest-app-bucket-01/main.py
          aws s3 cp db_load.py s3://rest-app-bucket-01/db_load.py
          aws s3 cp requirements.txt s3://rest-app-bucket-01/requirements.txt

      - name: Restart the Instance
        run: |
          aws ec2 reboot-instances --instance-ids $(aws ec2 describe-instances --filters "Name=tag:Name,Values=restapp" --query "Reservations[*].Instances[*].InstanceId" --output text)

