name: Data Update Pipeline

on:
  push:
     branches:
       - master
     paths:
      - restlist.json
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DYNAMODB_TABLE_NAME: "restaurants"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install AWS CLI
        run: pip install awscli boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Upload Data to DynamoDB
        run: |
          python -c "
          import json
          import boto3
          import os

          table_name = os.environ['DYNAMODB_TABLE_NAME']

          with open('restlist.json', 'r') as file:
              data = json.load(file)
          dynamodb = boto3.resource('dynamodb')

          table = dynamodb.Table(table_name)
          for item in data:
              response = table.put_item(Item=item)
              print(response)"

      - name: Copy Updated JSON to S3
        run: |
          aws s3 cp restlist.json s3://rest-app-bucket-01/restlist.json
